server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///sm_db
      username: root
      password: liyu.110
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  type-aliases-package: com.liyu.component
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-prefix: news_

jwt:
  token:
    tokenExpiration: 120
    tokenSignKey: headline123456